import os
import requests
import json
from dotenv import load_dotenv

# Load credentials
load_dotenv()

def generate_architectural_deep_dive():
    """
    Calls Groq Llama 3.1 8b to generate a deep-dive on the Supply Chain Dashboard architecture.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("Error: GROQ_API_KEY not found.")
        return

    prompt = """
    As a Senior Solution Architect, provide a deep-dive technical analysis of the 'SupplyChain360' dashboard.
    Cover:
    1. The benefits of using a Medallion Architecture (Bronze-Silver-Gold) for this retail use case.
    2. How to handle schema drift in the incoming telemetry data.
    3. Optimization strategies for Recharts with large real-time datasets.
    4. Security best practices for a public-facing monitoring UI.
    """

    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    data = {
        "model": "llama-3.1-8b-instant",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.5
    }

    print("--- Calling Groq Llama 3.1 8b ---")
    try:
        response = requests.post(url, headers=headers, data=json.dumps(data))
        response.raise_for_status()
        result = response.json()['choices'][0]['message']['content']
        print("\n=== Architectural Deep Dive (Generated by AI) ===\n")
        print(result)
        
        # Save to archive
        with open("archive/architectural_deep_dive.md", "w") as f:
            f.write("# Architectural Deep Dive: SupplyChain360\n")
            f.write(f"Generated via Groq Llama 3.1 8b on 2026-05-09\n\n")
            f.write(result)
        print("\n--- Result saved to archive/architectural_deep_dive.md ---")
        
    except Exception as e:
        print(f"Error calling API: {e}")

if __name__ == "__main__":
    generate_architectural_deep_dive()
